name: Quality Checks
on: push

env:
  NODE_VERSION: 16.13.1

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Lint Code
        run: npm run lint

  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm start
      - name: Provide Screenrecording as Artifact
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          retention-days: 10
          name: cypress-screenrecording
          path: |
            cypress/videos/*.mp4
